config_version = "0"

ignore_patterns = []
test_patterns = ["**/test/**", "**/spec/**"]

[sources.default]
repository = "https://github.com/qltyai/plugins.git"
tag = "v0.102.0"

[[plugin]]
name = "brakeman"

[[plugin]]
name = "checkov"
version = "3.2.49"

[[plugin]]
name = "markdownlint"
version = "0.31.1"

[[plugin]]
name = "osv-scanner"

[[plugin]]
name = "prettier"
version = "2.8.4"

[[plugin]]
name = "ripgrep"

[[plugin]]
name = "rubocop"

[[plugin]]
name = "trivy"

[[plugin]]
name = "trufflehog"

[[plugin]]
name = "yamllint"
